<template>
    <div>
        USD<br />
        AED<br />
        AFN<br />
        ALL<br />
        AMD<br />
        ANG<br />
        AOA<br />
        ARS<br />
        AUD<br />
        AWG<br />
        AZN<br />
        BAM<br />
        BBD<br />
        BDT<br />
        BGN<br />
        BHD<br />
        BIF<br />
        BMD<br />
        BND<br />
        BOB<br />
        BRL<br />
        BSD<br />
        BTN<br />
        BWP<br />
        BYN<br />
        BZD<br />
        CAD<br />
        CDF<br />
        CHF<br />
        CLF<br />
        CLP<br />
        CNH<br />
        CNY<br />
        COP<br />
        CRC<br />
        CUP<br />
        CVE<br />
        CZK<br />
        DJF<br />
        DKK<br />
        DOP<br />
        DZD<br />
        EGP<br />
        ERN<br />
        ETB<br />
        EUR<br />
        FJD<br />
        FKP<br />
        FOK<br />
        GBP<br />
        GEL<br />
        GGP<br />
        GHS<br />
        GIP<br />
        GMD<br />
        GNF<br />
        GTQ<br />
        GYD<br />
        HKD<br />
        HNL<br />
        HRK<br />
        HTG<br />
        HUF<br />
        IDR<br />
        ILS<br />
        IMP<br />
        INR<br />
        IQD<br />
        IRR<br />
        ISK<br />
        JEP<br />
        JMD<br />
        JOD<br />
        JPY<br />
        KES<br />
        KGS<br />
        KHR<br />
        KID<br />
        KMF<br />
        KRW<br />
        KWD<br />
        KYD<br />
        KZT<br />
        LAK<br />
        LBP<br />
        LKR<br />
        LRD<br />
        LSL<br />
        LYD<br />
        MAD<br />
        MDL<br />
        MGA<br />
        MKD<br />
        MMK<br />
        MNT<br />
        MOP<br />
        MRU<br />
        MUR<br />
        MVR<br />
        MWK<br />
        MXN<br />
        MYR<br />
        MZN<br />
        NAD<br />
        NGN<br />
        NIO<br />
        NOK<br />
        NPR<br />
        NZD<br />
        OMR<br />
        PAB<br />
        PEN<br />
        PGK<br />
        PHP<br />
        PKR<br />
        PLN<br />
        PYG<br />
        QAR<br />
        RON<br />
        RSD<br />
        RUB<br />
        RWF<br />
        SAR<br />
        SBD<br />
        SCR<br />
        SDG<br />
        SEK<br />
        SGD<br />
        SHP<br />
        SLE<br />
        SLL<br />
        SOS<br />
        SRD<br />
        SSP<br />
        STN<br />
        SYP<br />
        SZL<br />
        THB<br />
        TJS<br />
        TMT<br />
        TND<br />
        TOP<br />
        TRY<br />
        TTD<br />
        TVD<br />
        TWD<br />
        TZS<br />
        UAH<br />
        UGX<br />
        UYU<br />
        UZS<br />
        VES<br />
        VND<br />
        VUV<br />
        WST<br />
        XAF<br />
        XCD<br />
        XCG<br />
        XDR<br />
        XOF<br />
        XPF<br />
        YER<br />
        ZAR<br />
        ZMW<br />
        ZWL
    </div>
</template>

<script>
    export default {
        name: 'TextoGuia'
    };
</script>